// Generated by https://quicktype.io

export interface Presets {
  data: Preset[];
  meta: PresetMeta;
}

export interface Preset {
  id:         number;
  attributes: PresetAttributes;
}

export interface PresetAttributes {
  name:        string;
  value:       string;
  createdAt:   string;
  updatedAt:   string;
  publishedAt: string;
  isDefault:   boolean | null;
}

export interface PresetMeta {
  pagination: PresetPagination;
}

export interface PresetPagination {
  page:      number;
  pageSize:  number;
  pageCount: number;
  total:     number;
}
