// Generated by https://quicktype.io

export interface Presets {
  data: Preset[];
  meta: PresetMeta;
}

export interface Preset {
  id:         number;
  attributes: PresetAttributes;
}

export interface PresetAttributes {
  name:        string;
  value:       string;
  createdAt:   string;
  updatedAt:   string;
  publishedAt: string;
  isDefault:   boolean | null;
}

export interface PresetMeta {
  pagination: PresetPagination;
}

export interface PresetPagination {
  page:      number;
  pageSize:  number;
  pageCount: number;
  total:     number;
}


export interface ImageResponse {
  id:                number;
  name:              string;
  alternativeText:   null;
  caption:           null;
  width:             number;
  height:            number;
  formats:           ImageResponseFormats;
  hash:              string;
  ext:               string;
  mime:              string;
  size:              number;
  url:               string;
  previewUrl:        null;
  provider:          string;
  provider_metadata: null;
  createdAt:         string;
  updatedAt:         string;
}

export interface ImageResponseFormats {
  thumbnail: ImageResponseMedium;
  small:     ImageResponseMedium;
  medium:    ImageResponseMedium;
}

export interface ImageResponseMedium {
  name:   string;
  hash:   string;
  ext:    string;
  mime:   string;
  path:   null;
  width:  number;
  height: number;
  size:   number;
  url:    string;
}

