// Generated by https://quicktype.io

export interface Presets {
  data: Preset[];
  meta: PresetMeta;
}

export interface Preset {
  id:         number;
  attributes: PresetAttributes;
}

export interface PresetAttributes {
  name:        string;
  value:       string;
  createdAt:   string;
  updatedAt:   string;
  publishedAt: string;
  isDefault:   boolean | null;
}

export interface PresetMeta {
  pagination: PresetPagination;
}

export interface PresetPagination {
  page:      number;
  pageSize:  number;
  pageCount: number;
  total:     number;
}


export interface ImageResponse {
  id:                number;
  name:              string;
  alternativeText:   null;
  caption:           null;
  width:             number;
  height:            number;
  formats:           ImageResponseFormats;
  hash:              string;
  ext:               string;
  mime:              string;
  size:              number;
  url:               string;
  previewUrl:        null;
  provider:          string;
  provider_metadata: null;
  createdAt:         string;
  updatedAt:         string;
}

export interface ImageResponseFormats {
  thumbnail: ImageResponseMedium;
  small:     ImageResponseMedium;
  medium:    ImageResponseMedium;
}

export interface ImageResponseMedium {
  name:   string;
  hash:   string;
  ext:    string;
  mime:   string;
  path:   null;
  width:  number;
  height: number;
  size:   number;
  url:    string;
}

export interface CreateAikuResponse {
  data: CreateAikuResponseData;
  meta: CreateAikuResponseMeta;
}

export interface CreateAikuResponseData {
  id:         number;
  attributes: CreateAikuResponseAttributes;
}

export interface CreateAikuResponseAttributes {
  lineOne:     string;
  lineTwo:     string;
  lineThree:   string;
  createdAt:   string;
  updatedAt:   string;
  publishedAt: string;
}

export interface CreateAikuResponseMeta {
}


export interface GetAikuResponse {
  data: GetAikuResponseData;
  meta: GetAikuResponseMeta;
}

export interface GetAikuResponseData {
  id:         number;
  attributes: GetAikuResponseAttributes;
}

export interface GetAikuResponseAttributes {
  lineOne:     string;
  lineTwo:     string;
  lineThree:   string;
  createdAt:   string;
  updatedAt:   string;
  publishedAt: string;
  image:       GetAikuResponseImage;
  preset:      Preset;
  linkCard:    GetAikuResponseImage;
}

export interface GetAikuResponseImage {
  data: GetAikuResponseImageData;
}

export interface GetAikuResponseImageData {
  id:         number;
  attributes: GetAikuResponseAttributes;
}

export interface GetAikuResponseAttributes {
  name:              string;
  alternativeText:   null;
  caption:           null;
  width:             number;
  height:            number;
  formats:           GetAikuResponseFormats;
  hash:              string;
  ext:               string;
  mime:              string;
  size:              number;
  url:               string;
  previewUrl:        null;
  provider:          string;
  provider_metadata: null;
  createdAt:         string;
  updatedAt:         string;
}

export interface GetAikuResponseFormats {
  thumbnail: GetAikuResponseMedium;
  small:     GetAikuResponseMedium;
  medium:    GetAikuResponseMedium;
}

export interface GetAikuResponseMedium {
  name:   string;
  hash:   string;
  ext:    string;
  mime:   string;
  path:   null;
  width:  number;
  height: number;
  size:   number;
  url:    string;
}

export interface GetAikuResponsePreset {
  data: GetAikuResponsePresetData;
}

export interface GetAikuResponsePresetData {
  id:         number;
  attributes: GetAikuResponseAttributes;
}

export interface GetAikuResponseAttributes {
  name:        string;
  value:       string;
  createdAt:   string;
  updatedAt:   string;
  publishedAt: string;
  isDefault:   null;
}

export interface GetAikuResponseMeta {
}
